################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_eom(x, u, m, k, b):
    [z, zdot] = x.flatten()  # ensure 1D
    [tau] = u.flatten()  # ensure 1D
    eom = np.array([[zdot], [-b*zdot/m - k*z/m + tau/m]])
    return eom.squeeze()
