"""
Module Name: testMatrices

Description: This module tests the individual matrix calculation methods from
HummingbirdDynamics class against expected values. It uses the same test data
as testDynamics.py to ensure consistency.

Tests the following methods:
- calculate_M(x): Mass matrix
- calculate_C(x): Coriolis/centrifugal vector
- calculate_dP_dq(x): Gravity gradient vector
- calculate_tau(x, u): Generalized force vector

AUTOGENERATED by generate_test_matrices.py - DO NOT EDIT MANUALLY

To regenerate this file, run: python generate_test_matrices.py
"""

import numpy as np
from case_studies.H_hummingbird.dynamics import HummingbirdDynamics

# x = [phi, theta, psi, phidot, thetadot, psidot]
x_tests = np.array([
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.1, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.1, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.1, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.1],
    [0.1, 0.1, 0.1, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
    [-0.0752759286915825, 0.27042858384594964, 0.13919636508684308, 0.05919509051822197, -0.2063888157345381, -0.2064032877982784],
    [-0.2651498326990803, 0.21970568746496105, 0.06066900704592526, 0.12484354667762732, -0.28764930342251854, 0.28194591129719654],
    [0.19946558448025303, -0.1725965335930343, -0.19090501967573964, -0.1899572940879397, -0.11745465422427737, 0.014853858979342716],
    [-0.04083298881473052, -0.12526251588117485, 0.0671117368334277, -0.2163036836087749, -0.12471321087886911, -0.08018289402378498],
    [-0.026358009469778454, 0.17110557683580813, -0.18019573070498415, 0.008540663048166974, 0.05544874131722549, -0.27212975236800135],
    [0.06452691114086301, -0.19768552578762508, -0.26096904420883227, 0.2693313223519999, 0.2793792198447356, 0.18503840886987666],
    [-0.1172317384959776, -0.24139673159616967, 0.11053981590729411, -0.03590850375623922, -0.2267770590931327, -0.0028938539332378777],
    [-0.27936688733086895, 0.24559224124726925, -0.14473201103998984, 0.09751337061238918, -0.11297335434635342, 0.012040812706686499],
    [0.028026167605967767, -0.18908732668468375, 0.2817507766587351, 0.16507969401666872, 0.2636993649385135, 0.2368964102565893],
    [0.058739987286651085, 0.2531245410138701, -0.2469044987688483, -0.18241028254851288, -0.27286362665367714, -0.10480180154204138],
], dtype=np.float64).reshape(-1, 6, 1)

# u = [f_l, f_r]
u_tests = np.array([
    [0.0, 0.0],
    [0.1, 0.1],
    [0.15, 0.15],
    [0.1, 0.15],
    [0.15, 0.1],
    [0.05, 0.05],
    [0.2, 0.2],
    [0.0, 0.1],
    [0.1, 0.0],
    [0.05, 0.15],
    [0.07773545793789641, 0.05426980635477918],
    [0.1657475018303859, 0.07135066533871785],
    [0.05618690193747616, 0.1085392166316497],
    [0.02818484499495253, 0.16043939615080793],
    [0.014910128735954166, 0.19737738732010346],
    [0.1544489538593315, 0.03974313630683449],
    [0.00110442342472048, 0.16309228569096684],
    [0.14137146876952342, 0.14580143360819747],
    [0.15425406933718916, 0.014808930346818072],
    [0.07169314570885453, 0.023173811905025946],
], dtype=np.float64).reshape(-1, 2)

# Expected mass matrices M
M_expected = [
    np.array([
        [0.000189, 0.0, -0.0],
        [0.0, 0.012586017457999999, 0.0],
        [-0.0, 0.0, 0.012714686458]
    ]),
    np.array([
        [0.000189, 0.0, -0.0],
        [0.0, 0.012585429422046317, 5.860745258454309e-06],
        [-0.0, 5.860745258454309e-06, 0.012715274493953682]
    ]),
    np.array([
        [0.000189, 0.0, -1.8868515746250523e-05],
        [0.0, 0.012586017457999999, 0.0],
        [-1.8868515746250523e-05, 0.0, 0.012613324832323872]
    ]),
    np.array([
        [0.000189, 0.0, -0.0],
        [0.0, 0.012586017457999999, 0.0],
        [-0.0, 0.0, 0.012714686458]
    ]),
    np.array([
        [0.000189, 0.0, -0.0],
        [0.0, 0.012586017457999999, 0.0],
        [-0.0, 0.0, 0.012714686458]
    ]),
    np.array([
        [0.000189, 0.0, -0.0],
        [0.0, 0.012586017457999999, 0.0],
        [-0.0, 0.0, 0.012714686458]
    ]),
    np.array([
        [0.000189, 0.0, -0.0],
        [0.0, 0.012586017457999999, 0.0],
        [-0.0, 0.0, 0.012714686458]
    ]),
    np.array([
        [0.000189, 0.0, -1.8868515746250523e-05],
        [0.0, 0.012585429422046317, 5.831465943795477e-06],
        [-1.8868515746250523e-05, 5.831465943795477e-06, 0.0126139070074931]
    ]),
    np.array([
        [0.000189, 0.0, -0.0],
        [0.0, 0.012586017457999999, 0.0],
        [-0.0, 0.0, 0.012714686458]
    ]),
    np.array([
        [0.000189, 0.0, -1.8868515746250523e-05],
        [0.0, 0.012585429422046317, 5.831465943795477e-06],
        [-1.8868515746250523e-05, 5.831465943795477e-06, 0.0126139070074931]
    ]),
    np.array([
        [0.000189, 0.0, -5.049030460629985e-05],
        [0.0, 0.012585683767535782, -4.263718597525538e-06],
        [-5.049030460629985e-05, -4.263718597525538e-06, 0.011989201167724966]
    ]),
    np.array([
        [0.000189, 0.0, -4.119111261365715e-05],
        [0.0, 0.012581965796457355, -1.4562187134396082e-05],
        [-4.119111261365715e-05, -1.4562187134396082e-05, 0.012235481155596306]
    ]),
    np.array([
        [0.000189, 0.0, 3.245902628885908e-05],
        [0.0, 0.012583701020361647, 1.128854007015588e-05],
        [3.245902628885908e-05, 1.128854007015588e-05, 0.012416970621417403]
    ]),
    np.array([
        [0.000189, 0.0, 2.3612752182195754e-05],
        [0.0, 0.01258591914001561, -2.387614415109202e-06],
        [2.3612752182195754e-05, -2.387614415109202e-06, 0.012556041438462208]
    ]),
    np.array([
        [0.000189, 0.0, -3.218138629093928e-05],
        [0.0, 0.012585976477556505, -1.531703632726955e-06],
        [-3.218138629093928e-05, -1.531703632726955e-06, 0.012419871867956551]
    ]),
    np.array([
        [0.000189, 0.0, 3.7119687296192034e-05],
        [0.0, 0.01258577213915015, 3.7225867059811586e-06],
        [3.7119687296192034e-05, 3.7225867059811586e-06, 0.012322632792393514]
    ]),
    np.array([
        [0.000189, 0.0, 4.51821684945798e-05],
        [0.0, 0.012585210312245708, -6.654758326854214e-06],
        [4.51821684945798e-05, -6.654758326854214e-06, 0.012134238608438212]
    ]),
    np.array([
        [0.000189, 0.0, -4.595172829809753e-05],
        [0.0, 0.012581531305474786, -1.5169080647325606e-05],
        [-4.595172829809753e-05, -1.5169080647325606e-05, 0.012117731205962708]
    ]),
    np.array([
        [0.000189, 0.0, 3.5524925235362725e-05],
        [0.0, 0.012585971127634045, 1.6232211391571398e-06],
        [3.5524925235362725e-05, 1.6232211391571398e-06, 0.012355425179810732]
    ]),
    np.array([
        [0.000189, 0.0, -4.733129896570666e-05],
        [0.0, 0.01258581411924693, 3.3475123159333516e-06],
        [-4.733129896570666e-05, 3.3475123159333516e-06, 0.012077061738337825]
    ]),
]

# Expected Coriolis vectors C
C_expected = [
    np.array([-0.0, 0.0, 0.0]),
    np.array([-0.0, 0.0, 0.0]),
    np.array([-0.0, 0.0, 0.0]),
    np.array([-0.0, 0.0, 0.0]),
    np.array([-0.0, 0.0, 0.0]),
    np.array([-0.0, 0.0, 0.0]),
    np.array([-0.0, 0.0, 0.0]),
    np.array([-0.0, 0.0, 0.0]),
    np.array([-2.4800000000000004e-06, 2.480000000000001e-06, -1.3e-06]),
    np.array([-2.4553242418775322e-06, 1.2441630396577214e-05, -2.1400885576127327e-05]),
    np.array([-1.0166706995667924e-05, 0.00010852158111664248, -0.00022137881505367326]),
    np.array([1.888348966719963e-05, 0.00017919815699774511, 0.00035512588998697103]),
    np.array([5.739103353697402e-07, -1.56753172540933e-06, -9.000093526070142e-06]),
    np.array([-2.4807834423650114e-06, -3.7110682771016532e-06, 2.164115972951189e-05]),
    np.array([3.7932641427232843e-06, 0.00012579953651103154, 5.1443351702953357e-05]),
    np.array([-1.2374659777032908e-05, -5.553547228365236e-05, 0.0001932914957511457]),
    np.array([-5.094099702108259e-07, 1.1670799022199523e-07, 1.9724743664505493e-06]),
    np.array([1.1793223058675197e-07, 2.755574078799865e-07, 8.027068291954363e-06]),
    np.array([-1.518514867405272e-05, -9.598804851602632e-05, 0.00022915927015863658]),
    np.array([-6.632864689842652e-06, 3.132079183971705e-05, -0.000147249822892507]),
]

# Expected gravity gradient vectors dP/dq
dP_dq_expected = [
    np.array([0.0, 0.08331254333999999, 0.0]),
    np.array([0.0, 0.08331254333999999, 0.0]),
    np.array([0.0, 0.08289632764320604, 0.0]),
    np.array([0.0, 0.08331254333999999, 0.0]),
    np.array([0.0, 0.08331254333999999, 0.0]),
    np.array([0.0, 0.08331254333999999, 0.0]),
    np.array([0.0, 0.08331254333999999, 0.0]),
    np.array([0.0, 0.08289632764320604, 0.0]),
    np.array([0.0, 0.08331254333999999, 0.0]),
    np.array([0.0, 0.08289632764320604, 0.0]),
    np.array([0.0, 0.08028467317711821, 0.0]),
    np.array([0.0, 0.08130984599555385, 0.0]),
    np.array([0.0, 0.08207469868050316, 0.0]),
    np.array([0.0, 0.08265978156024176, 0.0]),
    np.array([0.0, 0.08209594031054787, 0.0]),
    np.array([0.0, 0.08168992887315726, 0.0]),
    np.array([0.0, 0.0808968978720527, 0.0]),
    np.array([0.0, 0.08081262575679185, 0.0]),
    np.array([0.0, 0.08182759661149364, 0.0]),
    np.array([0.0, 0.08065776161388896, 0.0]),
]

# Expected generalized force vectors tau
tau_expected = [
    np.array([0.0, 0.0, 0.0]),
    np.array([0.0, 0.07064529573473982, 0.0070881725819247985]),
    np.array([0.0, 0.1065, 0.0]),
    np.array([-0.005999999999999998, 0.08875, 0.0]),
    np.array([0.005999999999999998, 0.08875, 0.0]),
    np.array([0.0, 0.0355, 0.0]),
    np.array([0.0, 0.142, 0.0]),
    np.array([-0.012, 0.03532264786736991, 0.004724381621374275]),
    np.array([0.012, 0.0355, 0.0]),
    np.array([-0.011999999999999999, 0.07064529573473982, 0.008250762242986612]),
    np.array([0.002815878189974067, 0.04672916092696989, -0.004148403192919225]),
    np.array([0.011327620379000165, 0.08122838644997442, -0.023995588218271705]),
    np.array([-0.006282277763300825, 0.05731831049004135, 0.010336026346079778]),
    np.array([-0.01587054613870265, 0.06690578971613603, -0.004694855444881388]),
    np.array([-0.021896071030097917, 0.07533589101814607, 0.001771124897357243]),
    np.array([0.01376469810629964, 0.06879472205774319, 0.00706209798529666]),
    np.array([-0.019438543471949562, 0.05788974350726521, -0.011267056065235079]),
    np.array([-0.0005315957806408866, 0.09799394058186046, -0.0271386498490677]),
    np.array([0.01673341667884453, 0.0599937956287355, 0.004797115766011656]),
    np.array([0.00582232005645943, 0.033619686002043306, 0.00045600909518918775]),
]

# Create system for testing
system = HummingbirdDynamics()


def test_all_matrices(verbose=True):
    """Test all matrices for all test cases."""
    num_tests = len(x_tests)
    num_passed = 0
    tolerance = 1e-10
    
    for i, (x, u, M_exp, C_exp, dP_dq_exp, tau_exp) in enumerate(
        zip(x_tests, u_tests, M_expected, C_expected, dP_dq_expected, tau_expected),
        start=1
    ):
        test_passed = True
        failures = []
        
        # Test M matrix
        M_student = system.calculate_M(x)
        if not np.allclose(M_student, M_exp, atol=tolerance):
            test_passed = False
            failures.append("M")
        
        # Test C vector
        C_student = system.calculate_C(x)
        if not np.allclose(C_student, C_exp, atol=tolerance):
            test_passed = False
            failures.append("C")
        
        # Test dP_dq vector
        dP_dq_student = system.calculate_dP_dq(x)
        if not np.allclose(dP_dq_student, dP_dq_exp, atol=tolerance):
            test_passed = False
            failures.append("dP_dq")
        
        # Test tau vector
        tau_student = system.calculate_tau(x, u)
        if not np.allclose(tau_student, tau_exp, atol=tolerance):
            test_passed = False
            failures.append("tau")
        
        if test_passed:
            if verbose:
                print(f"Test {i:>2}: PASS")
            num_passed += 1
        else:
            print(f"Test {i:>2}: FAIL - check matrices: {', '.join(failures)}")
    
    print(f"\n{'='*60}")
    if num_passed == num_tests:
        print("Excellent work!! All matrix calculations passed!")
    else:
        print(f"{num_passed}/{num_tests} tests passed. Keep working on it!")
    print(f"{'='*60}\n")
    
    return num_passed == num_tests


def test_single_matrix(matrix_name, test_number=0, verbose=True):
    """
    Test a single matrix calculation for a specific test case.
    
    Args:
        matrix_name: One of 'M', 'C', 'dP_dq', 'tau'
        test_number: Index of test case (0-19)
        verbose: Whether to print detailed comparison
    """
    if test_number >= len(x_tests):
        print(f"Error: test_number must be 0-{len(x_tests)-1}")
        return False
    
    x = x_tests[test_number]
    u = u_tests[test_number]
    tolerance = 1e-10
    
    if matrix_name == 'M':
        expected = M_expected[test_number]
        student = system.calculate_M(x)
        name = "Mass matrix M"
    elif matrix_name == 'C':
        expected = C_expected[test_number]
        student = system.calculate_C(x)
        name = "Coriolis vector C"
    elif matrix_name == 'dP_dq':
        expected = dP_dq_expected[test_number]
        student = system.calculate_dP_dq(x)
        name = "Gravity gradient dP/dq"
    elif matrix_name == 'tau':
        expected = tau_expected[test_number]
        student = system.calculate_tau(x, u)
        name = "Generalized force tau"
    else:
        print(f"Error: matrix_name must be one of 'M', 'C', 'dP_dq', 'tau'")
        return False
    
    passed = np.allclose(student, expected, atol=tolerance)
    
    if verbose:
        print(f"\n{name} - Test {test_number}")
        print(f"State: {x.flatten()}")
        print(f"Input: {u.flatten()}")
        print(f"\nExpected:\n{expected}")
        print(f"\nStudent:\n{student}")
        
        if passed:
            print(f"\n✓ PASS")
        else:
            print(f"\n✗ FAIL")
            diff = student - expected
            print(f"\nDifference:\n{diff}")
            print(f"Max error: {np.max(np.abs(diff))}")
    
    return passed


if __name__ == "__main__":
    print("Testing all matrix calculations...\n")
    test_all_matrices(verbose=True)
    
    print("\nTo test individual matrices, use:")
    print("  test_single_matrix('M', test_number=0)")
    print("  test_single_matrix('C', test_number=5)")
    print("  test_single_matrix('dP_dq', test_number=10)")
    print("  test_single_matrix('tau', test_number=15)")